version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
    networks:
      - ws_network

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    networks:
      - ws_network

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    networks:
      - ws_network
       

  mail:
    image: catatnight/postfix
    ports:
      - "25:25"
    networks:
      ws_network:
        ipv4_address: "10.254.249.10"

volumes:
  db-store:

networks:
  ws_network:
    ipam:
     driver: default
     config:
      - subnet: 10.254.249.0/24