version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
    networks:
        - work-shops_default  

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    networks:
      - work-shops_default

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    networks:
      - work-shops_default
       

  mail:
    image: catatnight/postfix
    ports:
      - "25:25"
    networks:
      - work-shops_default

volumes:
  db-store:

networks:
  work-shops_default:
    ipam:
     driver: default
     config:
      - subnet: 10.254.249.0/24